name: Generate Space Shooter

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Yoshi-0921/github-contribution-grid-space-shooter@v1
        with:
          github_user_name: alba-alonso-dev
      - uses: actions/upload-artifact@v4
        with:
          name: space-shooter
          path: dist/
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
